version: '3'

services:
  main:
    build:
      context: .
      dockerfile: build/MyShortURL/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      dockerfile: build/db/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
